-- SQLite 建表腳本
-- 注意：SQLite 語法與 SQL Server 略有不同

CREATE TABLE IF NOT EXISTS JOB_APPLICATION (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    AppliedPosition TEXT NOT NULL,
    BirthDate TEXT NULL,
    MobilePhone TEXT NOT NULL,
    Email TEXT NULL,
    ContactAddress TEXT NULL,
    LanguageSkills_English TEXT NULL,
    LanguageSkills_Japanese TEXT NULL,
    Remark TEXT NULL,
    CreatedAt TEXT NOT NULL,
    CreatedIp TEXT NULL,
    UserAgent TEXT NULL
);

CREATE TABLE IF NOT EXISTS JOB_APPLICATION_EDUCATION (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    JobApplicationId INTEGER NOT NULL,
    SchoolName TEXT NOT NULL,
    Degree TEXT NOT NULL,
    FieldOfStudy TEXT NOT NULL,
    StartYear INTEGER NOT NULL,
    EndYear INTEGER NULL,
    FOREIGN KEY (JobApplicationId) REFERENCES JOB_APPLICATION(Id)
);

CREATE TABLE IF NOT EXISTS JOB_APPLICATION_CERTIFICATE (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    JobApplicationId INTEGER NOT NULL,
    CertificateName TEXT NOT NULL,
    ObtainedDate TEXT NOT NULL,
    FOREIGN KEY (JobApplicationId) REFERENCES JOB_APPLICATION(Id)
);

CREATE TABLE IF NOT EXISTS JOB_APPLICATION_EXPERIENCE (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    JobApplicationId INTEGER NOT NULL,
    CompanyName TEXT NOT NULL,
    Position TEXT NOT NULL,
    StartMonth INTEGER NOT NULL CHECK (StartMonth BETWEEN 1 AND 12),
    StartYear INTEGER NOT NULL,
    EndMonth INTEGER NULL CHECK (EndMonth BETWEEN 1 AND 12),
    EndYear INTEGER NULL,
    FOREIGN KEY (JobApplicationId) REFERENCES JOB_APPLICATION(Id)
);
