CREATE TABLE JOB_APPLICATION (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    AppliedPosition NVARCHAR(100) NOT NULL,
    BirthDate DATE NULL,
    MobilePhone NVARCHAR(20) NOT NULL,
    Email NVARCHAR(100) NULL,
    ContactAddress NVARCHAR(200) NULL,
    LanguageSkills_English NVARCHAR(50) NULL,
    LanguageSkills_Japanese NVARCHAR(50) NULL,
    Remark NVARCHAR(MAX) NULL,
    CreatedAt DATETIME NOT NULL,
    CreatedIp NVARCHAR(45) NULL,
    UserAgent NVARCHAR(200) NULL
);

CREATE TABLE JOB_APPLICATION_EDUCATION (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    JobApplicationId INT NOT NULL FOREIGN KEY REFERENCES JOB_APPLICATION(Id),
    SchoolName NVARCHAR(100) NOT NULL,
    Degree NVARCHAR(50) NOT NULL,
    FieldOfStudy NVARCHAR(100) NOT NULL,
    StartYear INT NOT NULL,
    EndYear INT NULL
);

CREATE TABLE JOB_APPLICATION_CERTIFICATE (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    JobApplicationId INT NOT NULL FOREIGN KEY REFERENCES JOB_APPLICATION(Id),
    CertificateName NVARCHAR(100) NOT NULL,
    ObtainedDate DATE NOT NULL
);

CREATE TABLE JOB_APPLICATION_EXPERIENCE (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    JobApplicationId INT NOT NULL FOREIGN KEY REFERENCES JOB_APPLICATION(Id),
    CompanyName NVARCHAR(100) NOT NULL,
    Position NVARCHAR(100) NOT NULL,
    StartMonth INT NOT NULL CHECK (StartMonth BETWEEN 1 AND 12),
    StartYear INT NOT NULL,
    EndMonth INT NULL CHECK (EndMonth BETWEEN 1 AND 12),
    EndYear INT NULL
);